### ISSUE TITLE
 get error : No module named mytodo.tools

### ISSUE THREAD

**Issue by sarla999** [mohamed-aziz/mytodo#3]
how to fix it , thanks.

**Comment by realazizk** [comment]
Hello, you installed mytodo from pip or you clonned the repository ?
Please try to upgrade pip install mytodo --upgrade

**Comment by sarla999** [comment]
I installed mytodo via clonned the repository . I will try pip install . thanks

**Comment by sarla999** [comment]
I install it via PIP and the new version is mytodo-0.2.3 . when i open mytodo_cli get the error. ./mytodo_cli
  File "./mytodo_cli", line 57
    print u'%i) %s, %s %s' % (row[3], row[4].encode('utf-8'), Fore.YELLOW+dayz+Fore.RESET,
                         ^
SyntaxError: invalid syntax

**Comment by realazizk** [comment]
Sorry but mytodo is not yet compatible with python3.

**Comment by sarla999** [comment]
with python2 still get error: No module named mytodo.tools . where I can find it or I can get it from git repository and place it to lib dir?

**Comment by realazizk** [comment]
Hello I made a video on how to install mytodo https://www.youtube.com/watch?v=_eB4mpw1vWM

sorry for the delay.

**Comment by sarla999** [comment]
thank you man . I got how to fix it .
