### ISSUE TITLE
Get Error: Could not connect to mytodo server :(

### ISSUE THREAD

**Issue by ZemingLiu** [mohamed-aziz/mytodo#4]
I use pip installed mytodo in my raspberry pi. I edited  mytodoconfig.json in my home directory as following:

```
{
    "username" : "mohamed",
    "password" : "root",
    "host"     : "http://localhost:5000/"
}
```

And I also edited the database path in the config.py as following:

```
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////home/pi/todo.db'  
```

Then I run the server, but when I use mytodo_cli,there will be an error：

```
Could not connect to mytodo server :(
```

How should I do to solve this problem?
## Thanks.
- OS: Debian 8
- Linux kernel version: 4.1.10
- mytodo version: Lasted Release

**Comment by realazizk** [comment]
Hello I think issue occurs because of your database file is not initialized anyways this is fixed now you should update from pip, thanks for reporting this issue.

**Comment by ZemingLiu** [comment]
Yes, you are right! Problem solved.

```
       Best regrads
```
